### ISSUE TITLE
Is it possible to create an SRIOV interface by defining vlan value inside Pod definition?

### ISSUE THREAD

**Issue by PrahladaHerle** [intel/sriov-network-device-plugin#242]
Defining vlan tag in SR-IOV CRD and using that in the Pod definition is working fine.

If i don't define vlan tag in SR-IOV CRD and try to pass vlan value as an option in Pod definition, it seems to get ignored.

I was testing with following configuration.
OS: CentOS-7
Kernel: 3.10.0-rt56 (realtime kernel)
Docker: 19.03.11
Kubernetes: v1.18.3
Ethernet card info: 3b:00.1 Ethernet controller [0200]: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ [8086:1583] (rev 02)
Using Multus/SR-IOV device plugin

```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {
            "name": sriov-net,
            "vlan": 200
        }
]'
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      requests:
        intel.com/intel_sriov_netdevice: '1'
      limits:
        intel.com/intel_sriov_netdevice: '1'
```
